# Generated by Django 4.1.5 on 2023-01-31 10:17

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=500, verbose_name='Title')),
                ('item_img', models.CharField(max_length=5000, verbose_name='IMG')),
                ('item_body', ckeditor.fields.RichTextField(verbose_name='Body')),
                ('item_price', models.FloatField(default=10.0, verbose_name='Price')),
                ('item_date', models.DateField(verbose_name='Date')),
                ('isdigital', models.BooleanField(default=False, verbose_name='Digital')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('ordered_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Cart',
            },
        ),
    ]
